mj=Department.create(name: '民生加银资产管理有限公司')
jh=Department.create(name: '金融合作事业部', sup_department: mj)
jh1=Department.create(name: '金融合作一部', sup_department: jh)
jh2=Department.create(name: '金融合作二部', sup_department: jh)
jh3=Department.create(name: '金融合作三部', sup_department: jh)
jh4=Department.create(name: '金融合作四部', sup_department: jh)
jh5=Department.create(name: '金融合作五部', sup_department: jh)
jhcx1=Department.create(name: '创新业务一部', sup_department: jh)
jhcx2=Department.create(name: '创新业务二部', sup_department: jh)
hzzc=Department.create(name: '合作支持部', sup_department: jh)


chenzhihua =User.create(username: :陈志华, email: 'chenzhihua@msjyamc.com.cn', password: '12345678', usertype: 'admin')
fuyingxin =User.create(username: :傅颖新 ,email: 'fuyingxin@msjyamc.com.cn', password: '12345678',usertype: 'staff')
dengliping =User.create(username: :邓丽平 ,email: 'dengliping@msjyamc.com.cn', password: '12345678',usertype: 'staff')

DepartmentUser.create(department: jh, user: chenzhihua, role: 'admin')
DepartmentUser.create(department: jh, user: fuyingxin, role: 'admin')
DepartmentUser.create(department: jh, user: dengliping, role: 'admin')

wangjinfeng =User.create(username: :王金凤 ,email: 'wangjinfeng@msjyamc.com.cn', password: '12345678',usertype: 'staff')
shiweisi =User.create(username: :史维思 ,email: 'shiweisi@msjyamc.com.cn', password: '12345678',usertype: 'staff')
qiuli =User.create(username: :邱莉 ,email: 'qiuli@msjyamc.com.cn', password: '12345678',usertype: 'staff')
chenfan =User.create(username: :陈凡 ,email: 'chenfan@msjyamc.com.cn', password: '12345678',usertype: 'staff')
luozichen =User.create(username: :罗自琛 ,email: 'luozichen@msjyamc.com.cn', password: '12345678',usertype: 'staff')
huangjian =User.create(username: :黄健 ,email: 'huangjian@msjyamc.com.cn', password: '12345678',usertype: 'staff')
teriwen =User.create(username: :特日文 ,email: 'teriwen@msjyamc.com.cn', password: '12345678',usertype: 'staff')
DepartmentUser.create(department: jh1, user: wangjinfeng, role: 'admin')
DepartmentUser.create(department: jh1, user: shiweisi, role: 'staff')
DepartmentUser.create(department: jh1, user: qiuli, role: 'staff')
DepartmentUser.create(department: jh1, user: chenfan, role: 'staff')
DepartmentUser.create(department: jh1, user: luozichen, role: 'staff')
DepartmentUser.create(department: jh1, user: huangjian, role: 'staff')
DepartmentUser.create(department: jh1, user: teriwen, role: 'staff')

yuyong =User.create(username: :于勇 ,email: 'yuyong@msjyamc.com.cn', password: '12345678',usertype: 'staff')
libin =User.create(username: :李彬 ,email: 'libin@msjyamc.com.cn', password: '12345678',usertype: 'staff')
houzhen =User.create(username: :侯震 ,email: 'houzhen@msjyamc.com.cn', password: '12345678',usertype: 'staff')
liuyanze =User.create(username: :刘彦泽 ,email: 'liuyanze@msjyamc.com.cn', password: '12345678',usertype: 'staff')
kongyilong =User.create(username: :孔一龙 ,email: 'kongyilong@msjyamc.com.cn', password: '12345678',usertype: 'staff')
DepartmentUser.create(department: jh2, user: yuyong, role: 'admin')
DepartmentUser.create(department: jh2, user: libin, role: 'staff')
DepartmentUser.create(department: jh2, user: houzhen, role: 'staff')
DepartmentUser.create(department: jh2, user: liuyanze, role: 'staff')
DepartmentUser.create(department: jh2, user: kongyilong, role: 'staff')

songlin =User.create(username: :宋琳 ,email: 'songlin@msjyamc.com.cn', password: '12345678',usertype: 'staff')
wangtao =User.create(username: :王涛 ,email: 'wangtao@msjyamc.com.cn', password: '12345678',usertype: 'staff')
liwei =User.create(username: :李炜 ,email: 'liwei@msjyamc.com.cn', password: '12345678',usertype: 'staff')
daigang =User.create(username: :戴刚 ,email: 'daigang@msjyamc.com.cn', password: '12345678',usertype: 'staff')
wangyue =User.create(username: :王越 ,email: 'wangyue@msjyamc.com.cn', password: '12345678',usertype: 'staff')
DepartmentUser.create(department: jh3, user: songlin, role: 'admin')
DepartmentUser.create(department: jh3, user: wangtao, role: 'staff')
DepartmentUser.create(department: jh3, user: liwei, role: 'staff')
DepartmentUser.create(department: jh3, user: daigang, role: 'staff')
DepartmentUser.create(department: jh3, user: wangyue, role: 'staff')

juhuiling =User.create(username: :鞠慧灵 ,email: 'juhuiling@msjyamc.com.cn', password: '12345678',usertype: 'staff')
guowei =User.create(username: :郭伟 ,email: 'guowei@msjyamc.com.cn', password: '12345678',usertype: 'staff')
guozhehui =User.create(username: :郭哲荟 ,email: 'guozhehui@msjyamc.com.cn', password: '12345678',usertype: 'staff')
DepartmentUser.create(department: jh4, user: juhuiling, role: 'admin')
DepartmentUser.create(department: jh4, user: guowei, role: 'staff')
DepartmentUser.create(department: jh4, user: guozhehui, role: 'staff')

dengliping =User.create(username: :邓丽平 ,email: 'dengliping@msjyamc.com.cn', password: '12345678',usertype: 'staff')
zhaoyuheng =User.create(username: :赵玉恒 ,email: 'zhaoyuheng@msjy.amc,com,cn', password: '12345678',usertype: 'staff')
liuchao =User.create(username: :刘超 ,email: 'liuchao@msjyamc.com.cn', password: '12345678',usertype: 'staff')
luochen =User.create(username: :骆晨 ,email: 'luochen@msjyamc.com.cn', password: '12345678',usertype: 'staff')
zhouyujie =User.create(username: :周煜杰 ,email: 'zhouyujie@msjyamc.com.cn', password: '12345678',usertype: 'staff')
kongmengfei =User.create(username: :孔梦飞 ,email: 'kongmengfei@msjyamc.com.cn', password: '12345678',usertype: 'staff')
DepartmentUser.create(department: jh5, user: dengliping, role: 'admin')
DepartmentUser.create(department: jh5, user: zhaoyuheng, role: 'staff')
DepartmentUser.create(department: jh5, user: liuchao, role: 'staff')
DepartmentUser.create(department: jh5, user: luochen, role: 'staff')
DepartmentUser.create(department: jh5, user: zhouyujie, role: 'staff')
DepartmentUser.create(department: jh5, user: kongmengfei, role: 'staff')

zhoulina =User.create(username: :周丽娜 ,email: 'zhoulina@msjyamc.com.cn', password: '12345678',usertype: 'staff')
zhanglan =User.create(username: :张岚 ,email: 'zhanglan@msjyamc.com.cn', password: '12345678',usertype: 'staff')
DepartmentUser.create(department: jhcx1, user: zhoulina, role: 'admin')
DepartmentUser.create(department: jhcx2, user: zhanglan, role: 'staff')

xuyang =User.create(username: :徐旸 ,email: 'xuyang@msjyamc.com.cn', password: '12345678',usertype: 'staff')
wangliang =User.create(username: :王亮 ,email: 'wangliang@msjyamc.com.cn', password: '12345678',usertype: 'staff')
zhaoyujun =User.create(username: :赵玉君 ,email: 'zhaoyujun@msjyamc.com.cn', password: '12345678',usertype: 'staff')
DepartmentUser.create(department: jhcx2, user: xuyang, role: 'admin')
DepartmentUser.create(department: jhcx2, user: wangliang, role: 'staff')
DepartmentUser.create(department: jhcx2, user: zhaoyujun, role: 'staff')

liangfeng =User.create(username: :梁奉 ,email: 'liangfeng@msjyamc.com.cn', password: '12345678',usertype: 'staff')
huxinyang =User.create(username: :胡新阳 ,email: 'huxinyang@msjyamc.com.cn', password: '12345678',usertype: 'staff')
zhuyonglin =User.create(username: :朱永林 ,email: 'zhuyonglin@msjyamc.com.cn', password: '12345678',usertype: 'staff')
sunchenke =User.create(username: :孙晨珂 ,email: 'sunchenke@msjyamc.com.cn', password: '12345678',usertype: 'staff')
zhangjian =User.create(username: :张健 ,email: 'zhangjian@msjyamc.com.cn', password: '12345678',usertype: 'staff')
zhouchen =User.create(username: :周晨 ,email: 'zhouchen@msjyamc.com.cn', password: '12345678',usertype: 'staff')
gengjiachao =User.create(username: :耿佳超 ,email: 'gengjiachao@msjyamc.com.cn', password: '12345678',usertype: 'staff')
liuxiao =User.create(username: :刘晓 ,email: 'liuxiao@msjyamc.com.cn', password: '12345678',usertype: 'staff')
guorui =User.create(username: :郭蕊 ,email: 'guorui@msjyamc.com.cn', password: '12345678',usertype: 'staff')
xidan =User.create(username: :席丹 ,email: 'xidan@msjyamc.com.cn', password: '12345678',usertype: 'staff')
zhangxuefei =User.create(username: :张雪菲 ,email: 'zhangxuefei@msjyamc.com.cn', password: '12345678',usertype: 'staff')
lixiaohan =User.create(username: :李潇涵 ,email: 'lixiaohan@msjyamc.com.cn', password: '12345678',usertype: 'staff')
DepartmentUser.create(department: hzzc, user: liangfeng, role: 'admin')
DepartmentUser.create(department: hzzc, user: huxinyang, role: 'staff')
DepartmentUser.create(department: hzzc, user: zhuyonglin, role: 'staff')
DepartmentUser.create(department: hzzc, user: sunchenke, role: 'staff')
DepartmentUser.create(department: hzzc, user: zhangjian, role: 'staff')
DepartmentUser.create(department: hzzc, user: zhouchen, role: 'staff')
DepartmentUser.create(department: hzzc, user: gengjiachao, role: 'staff')
DepartmentUser.create(department: hzzc, user: liuxiao, role: 'staff')
DepartmentUser.create(department: hzzc, user: guorui, role: 'staff')
DepartmentUser.create(department: hzzc, user: xidan, role: 'staff')
DepartmentUser.create(department: hzzc, user: zhangxuefei, role: 'staff')
DepartmentUser.create(department: hzzc, user: lixiaohan, role: 'staff')
